[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "bin/railway-start"
healthcheckPath = "/healthcheck"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
RAILS_ENV = "production"
RACK_ENV = "production"

[[services]]
name = "web" 