services:
  - type: web
    name: our_gruuv-web
    env: ruby
    buildCommand: bundle install && bundle exec rake db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false

  - type: redis
    name: our_gruuv-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow Render services (default, modify as needed)

  - type: worker
    name: our_gruuv-worker
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow Render services (default, modify as needed)
