services:
  - type: web
    name: our_gruuv-web
    env: ruby
    buildCommand: bundle install && bundle exec rake db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false

  - type: key_value
    name: our_gruuv-valkey
    plan: free  # Valkey is Redis-compatible and free on Render
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow Render services

  - type: worker
    name: our_gruuv-worker
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
